theme: jekyll-theme-hacker
exclude: ['cTrain/notes/offline', 'servers', 'ProceSSingSketchBook/examples' , 'ProceSSingSketchBook/libraries', 'ProceSSingSketchBook/templates','ProceSSingSketchBook/modes']
