version: "2"
plugins:
  duplication:
    enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
checks:
  method-complexity:
    config:
      threshold: 10
  argument-count:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 300

